language: python
python:
  - "3.6"
services:
  - docker
install:
  - pip install -r requirements.txt
  - pip install coveralls
env:
  global:
    - SUPPORTED_LANGUAGES="en|pt"
    - BOTHUB_NLP_LANGUAGE_QUEUE="en"
    - BOTHUB_NLP_SERVICE_WORKER=true
before_script:
  - python scripts/download_spacy_models.py en-BERT
script:
  - flake8
  - travis_wait coverage run -m unittest discover bothub_nlp_nlu_worker/tests
after_success:
  - coveralls
